project:
  type: website
  output-dir: docs

# Meta
description-meta: "Dennis Baidoo"
author-meta: "Dennis Baidoo"

website:
  title: "Dennis Baidoo"
  image: "files/images/PIWC.JPG"
  description: "Oustanding Student"
 
  navbar:
    background: blue  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      # - text: About
      #   menu:
      #     - text: News
      #       href: posts.qmd#category=news
      #     - text: Events
      #       href: posts.qmd#category=event      
      #     - text: Contact
      #       href: contact.qmd             
      - text: Research
        href: publications.qmd
          # - text: Selected Papers
          #   href: posts.qmd#category=paper
          # - text: Grants
          #   href: projects.qmd                                
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        href: teaching.qmd
      - text: Presentations
        href: posts.qmd#category=presentation                   
      - text: Awards and Honors   # Comment the Group part out to remove the Group page
        href: Awards.qmd

    right: 
      - text: CV
        href: files/Baidoo_CV.pdf
      - icon: github
        href: https://github.com/dbaidoo/dbaidoo.github.io
        target: _blank
     
  
  page-navigation: true
  
  page-footer: 
    left: "[DennisBaidoo](https://github.com/dbaidoo/dbaidoo.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built with [Quarto](https://github.com/drganghe/quarto-academic-website-template), adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/dbaidoo/dbaidoo.github.io
        target: _blank
      
      
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

